apiVersion: v1
kind: Service
metadata:
  name: nats-consumer
spec:
  ports:
    - port: 8082
  type: NodePort
  selector:
    app: nats-consumer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-consumer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nats-consumer
  template:
    metadata:
      labels:
        app: nats-consumer
    spec:
      containers:
        - name: nats-consumer
          image: nats-consumer
          ports:
            - containerPort: 8082
          imagePullPolicy: IfNotPresent
